name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pdfplumber>=0.7.0
  - python-docx>=0.8.11
  - beautifulsoup4>=4.11.1
  - pandas>=1.5.0
  - requests>=2.28.0
  - pip
  - pip:
    - markdownify>=0.11.0
    - openai>=1.0.0
    - -e .